[package]
name = "gu-random"
version = "0.1.0"
authors = ["Piotr Chromiec <tworec@golem.network>"]

[dependencies]
rand = "0.5"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "random"
harness = false
